# Generated by Django 4.1.3 on 2022-11-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monography',
            name='summary',
            field=models.TextField(max_length=100),
        ),
    ]
