# Generated by Django 4.1.3 on 2022-11-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0003_alter_monography_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monography',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monografias.author'),
        ),
    ]
